### ISSUE TITLE
Invalid Argument Supplied - Installation Error

### ISSUE THREAD

**Issue by imran300** [nowendwell/laravel-terms#13]
![image_2021-05-07_083332](https://user-images.githubusercontent.com/7050400/117394098-f0d7a780-af0e-11eb-9d7c-b9ee796ab6c3.png)

**Comment by modernben** [comment]
@imran300 Did you run vendor publish?

**Comment by imran300** [comment]
@modernben its not installing. The vendor Publish is the second step you mentioned..

**Comment by nowendwell** [comment]
@imran300 Okay go ahead and try again. Fixed an issue in the service provider.

**Comment by nowendwell** [comment]
Glad it's working now.
