### ISSUE TITLE
require php ^7.3 -> your php version (8.1.17) does not satisfy that requirement.

### ISSUE THREAD

**Issue by madfortech** [nowendwell/laravel-terms#18]
![Capture](https://github.com/nowendwell/laravel-terms/assets/21261716/776472cf-c6ea-40dd-9a78-6d74a6874d65)

PHP 8.1.17 (cli) (built: Mar 14 2023 23:07:43) (ZTS Visual C++ 2019 x64)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies

E:\xampp\htdocs\PersonalApp>php artisan --version
Laravel Framework 10.37.1

Help me

**Comment by nowendwell** [comment]
Apologies, we had a PR for Laravel 10 compatibility but I guess I didn't do a release. Just tested it and it looks good.
