### ISSUE TITLE
Publish migrations

### ISSUE THREAD

**Issue by nowendwell** [nowendwell/laravel-terms#4]
I would prefer migrations to be publishable. not a problem when I can update the migration later, but since most of the time I know what changes i want to add, publishable migrations work better for me

**Comment by nowendwell** [comment]
@cyrillkalita Yeah I could get on board with that. Any opposition to including spatie/laravel-package-tools ?

**Comment by cyrillkalita** [comment]
They are pretty good with maintaining their packages, so adding one more dependency should not be a problem. Have you tried it elsewhere yet?

**Comment by cyrillkalita** [comment]
Ok, I have and its is nice and clean and well through through. Definitely an improvement
