### ISSUE TITLE
Make name of route configurable

### ISSUE THREAD

**Issue by nowendwell** [nowendwell/laravel-terms#5]
@cyrillkalita Do you mean the path?

Instead of /latest? Or do you mean the actual route name (terms.show)?

If it is the latter can you give me some background on why this would be needed?

**Comment by cyrillkalita** [comment]
Yeah, makes sense. Any new agreed to will supersede any past ones and there is no apparent reason or need for one to be able to view them (even with ?version=_xyz_). I am overthinking it.

However, some sites offer the link as `tos`, ther others will have it spelled out like `terms-and-conditions` or, `terms`. `terms/latest` could be configured to reflect that need, I think.

Also, on a related note: maybe add this to readme? _as in generate terms for free here: [getterms.io](https://getterms.io/)_
